<?php
namespace HEAT;

const OPTION_SETUP = 100;
const OPTION_SETUP_BEGINNER = 0;
const OPTION_SETUP_STANDARD = 1;
const OPTION_SETUP_FREE = 2;
const OPTION_SETUP_SEED = 3;
const OPTION_SETUP_AUCTION = 4;

const OPTION_CIRCUIT = 102;

const OPTION_LEGEND = 110;

/**
 * User preferences
 */
const OPTION_CONFIRM = 103;
const OPTION_CONFIRM_DISABLED = 0;
const OPTION_CONFIRM_TIMER = 1;
const OPTION_CONFIRM_ENABLED = 2;
