<?php

namespace HEAT;

const OPTION_SETUP = 100;
const OPTION_SETUP_FIRST_GAME = 0;
const OPTION_SETUP_BEGINNER = 1;
const OPTION_SETUP_STANDARD = 2;
const OPTION_SETUP_CHAMPIONSHIP = 3;

const OPTION_CIRCUIT = 102;
const OPTION_CIRCUIT_USA = 1;
const OPTION_CIRCUIT_ITALIA = 2;
const OPTION_CIRCUIT_GB = 3;
const OPTION_CIRCUIT_FRANCE = 4;
const OPTION_CIRCUIT_JAPAN = 5;
const OPTION_CIRCUIT_RANDOM = 99;
const OPTION_CIRCUIT_CUSTOM = 100;

const OPTION_NBR_LAPS = 103;

const OPTION_GARAGE_MODULE = 104;
const OPTION_GARAGE_MODULE_CHAMPIONSHIP = 108;
const OPTION_DISABLED = 0;
const OPTION_GARAGE_BASIC = 1;
const OPTION_GARAGE_ADVANCED = 2;
const OPTION_GARAGE_MIXED = 3;

const OPTION_GARAGE_CHOICE = 105;
const OPTION_GARAGE_RANDOM = 1;
const OPTION_GARAGE_DRAFT = 2;
const OPTION_GARAGE_SNAKE_DRAFT = 3;

const OPTION_WEATHER_MODULE = 106;
const OPTION_WEATHER_ENABLED = 1;

const OPTION_CHAMPIONSHIP = 107;
const OPTION_CHAMPIONSHIP_SEASON_61 = 0;
const OPTION_CHAMPIONSHIP_SEASON_62 = 1;
const OPTION_CHAMPIONSHIP_SEASON_63 = 2;
const OPTION_CHAMPIONSHIP_RANDOM = 99;
const OPTION_CHAMPIONSHIP_CUSTOM = 100;

const OPTION_LEGEND = 110;
const OPTION_LEGEND_PRO = 109;
const OPTION_AGGRESSIVE_LEGENDS = 111;

/**
 * User preferences
 */
const OPTION_CONFIRM_HEAT_COST = 201;
const OPTION_CONFIRM_HEAT_COST_ENABLED = 0;
const OPTION_CONFIRM_HEAT_COST_DISABLED = 1;
